### ISSUE TITLE
Update LPT once bug with listing solved

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/DeepSeeWeb#109]
The bug https://github.com/intersystems-ru/LightPivotTable/issues/14

**Comment by ZitRos** [comment]
Please see [#14](https://github.com/intersystems-ru/LightPivotTable/issues/14) in LPT repository.

DeepSeeWeb uses `changeBasicMDX` and after setting filter the second time, MDX changes **externally** to `DRILLTHROUGH`.

**Comment by ZitRos** [comment]
Also it was discussed before in [LightPivotTable/issues/10](https://github.com/intersystems-ru/LightPivotTable/issues/10) but didn't yield any results.

**Comment by gnibeda** [comment]
updated
