### ISSUE TITLE
Can't change namespace at home screen (DSW 2.1.35)

### ISSUE THREAD

**Issue by AngeloBBraga** [intersystems-ru/DeepSeeWeb#129]
Hi !

I recently installed DSW 2.1.35 on IRIS 2019.1.0.510.4 and in the home screen ( http://localhost:52773/dsw/index.html ) I can't change the Sample namespace to the other Analytics enabled ones:
DSW home screen:
![image](https://user-images.githubusercontent.com/54040112/68301061-e91b1680-007d-11ea-860d-9704e480e37c.png)
Analytics enabled namespaces:
![image](https://user-images.githubusercontent.com/54040112/68301210-3a2b0a80-007e-11ea-9977-482a77721260.png)

Thanks in advance.

Angelo Braga

**Comment by evshvarov** [comment]
Hi Angelo!
try http://localhost:52773/dsw/index.html?ns=LABORATORYANALYTICS

**Comment by AngeloBBraga** [comment]
Hi Evgeny.

Here is the print:

![image](https://user-images.githubusercontent.com/54040112/68306306-0e148700-0088-11ea-9f86-fd50e91795dc.png)

**Comment by evshvarov** [comment]
My bad,  html#!?ns=
Like here
https://analytics.community.intersystems.com/dswpub/index.html#!/?ns=COMMUNITYPUBLIC&embed=1

**Comment by AngeloBBraga** [comment]
Hi Evgeny.

Worked fine:
![image](https://user-images.githubusercontent.com/54040112/68320080-17a8e980-009e-11ea-8fec-08191c0ff0e5.png)

Thanks a lot.

Angelo Braga
