### ISSUE TITLE
GetMembersForFilter() when input a search string in a filter box

### ISSUE THREAD

**Issue by tnitzsch** [intersystems-ru/DeepSeeWeb#13]
Currently search in DSW Dashboards is performed on values that have been received from mdx2json. By default there is a limit of 2500 distinct values since 2013.2. 
It would be great if after input a search value, then up to 2500 items whose displayed name starts with this value will be listed. ATM the search is applied to the shortened list.

**Comment by eduard93** [comment]
For example like this:
1. If there's less than 2500 filter values, then search locally on a client (as in is)
2. If there's 2500 filter values, then send new request for filter values with this body:
```
{ 
    "DataSource": same as the 1st request,
    "Values":1,
    "Search": "user's search text"
}
```

**Comment by gnibeda** [comment]
This should be done by #6 fix
