### ISSUE TITLE
Chart widget doesn't show the line

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/DeepSeeWeb#15]
Testcase is available [here](http://146.185.143.59/index.html#/d/test/ChartBug.dashboard?ns=SAMPLES)
The column is shown in pivot table, though.

**Comment by evshvarov** [comment]
Testcase is here: http://146.185.143.59/index.html#/d/test/ChartBug.dashboard?ns=SAMPLES

**Comment by gnibeda** [comment]
fixed in https://github.com/intersystems-ru/DeepSeeWeb/commit/c993f9c05434e67bd47701f9e31406561fba985c
