### ISSUE TITLE
Can't load addon alert

### ISSUE THREAD

**Issue by daimor** [intersystems-ru/DeepSeeWeb#20]
with 2.0.7 release I'm getting 'Can't load addon' alert, even I don't have any addons, yet.

**Comment by eduard93** [comment]
Security problems probably.
Can you please provide:
- Security level
- Roles for user who accesses DSW?

**Comment by daimor** [comment]
I've been working with user which have %ALL role

**Comment by eduard93** [comment]
Can you post `http://host:port/MDX2JSON/Test?Debug` output?

**Comment by daimor** [comment]
`{
	"Cache":"Cache for Windows (x86-64) 2016.1 (Build 656U) Fri Mar 11 2016 17:42:42 EST",
	"DefaultApp":"\/csp\/mdx2json",
	"Mappings": {
		"Mapped":["%SYS","ENSDEMO","ENSEMBLE","FNBAMISGW","FNBBRD","FNBCS","FNBDS","FNBEMPI","FNBISAC","FNBKOM","FNBLIB","FNBLINKS","FNBMDXGW","FNBMPAGW","FNBMSGBANK","FNBPORTALEK","FNBREGISTRY","FNBTEST","FNBWS","MDX2JSON","SAMPLES","USER"
		],
		"Unmapped":["DOCBOOK"
		]
	},
	"Namespace":"MDX2JSON",
	"Parent":"c7c592b12d45d04e764bb7bf6c5807a45469a5c7",
	"ParentTS":"2017-02-02 12:52:59.902",
	"Request": {
		"URL":"\/MDX2JSON\/Test",
		"PageName":"Test",
		"URLPrefix":"",
		"UserAgent":"Mozilla\/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/55.0.2883.87 Safari\/537.36",
		"RequestId":"219320",
		"ContentType":"",
		"CharSet":"",
		"Content":"",
		"Method":"GET",
		"Protocol":"HTTP\/1.1",
		"Secure":false,
		"GatewayApplication":"\/",
		"GatewayConnectionName":"LOCAL",
		"GatewaySessionIdSource":3,
		"GatewayNewId":false,
		"GatewayBuild":"661.1601.1554d",
		"GatewayFunctions":"7",
		"GatewaySessionCookie":"CSPSESSIONID-SP-57772-UP-MDX2JSON-",
		"GatewayInstanceName":"ziminiar:57772",
		"GatewayError":"",
		"Application":"\/mdx2json\/",
		"CSPGatewayRequest":true,
		"GatewayTimeout":60,
		"AppData":"",
		"AppMatch":"\/mdx2json\/",
		"Class":"MDX2JSON.REST",
		"Service":"REST",
		"ProcessedRequestType":true
	},
	"Response": {
		"HTTPVersion":"",
		"Status":"200 OK",
		"Redirect":"",
		"ServerSideRedirect":"",
		"ContentType":"application\/json",
		"CharSet":"utf-8",
		"CookiePath":"\/MDX2JSON\/",
		"HeaderCharSet":"",
		"ContentLength":"",
		"NoCharSetConvert":false,
		"UseHttpOnly":true,
		"InProgress":1,
		"Expires":"Thu, 29 Oct 1998 17:04:19 GMT",
		"VaryByParam":"",
		"TraceDump":false,
		"OutputSessionToken":true,
		"UseASPredirect":false,
		"Timeout":"",
		"Language":"en-us",
		"Domain":"",
		"GzipOutput":null,
		"AvoidPartitionCleanup":false
	},
	"Roles":"%All",
	"SessionId":"ToE6aST1Pz",
	"Status":"OK",
	"User":"dmitry.maslennikov",
	"Version":2.2
}`

**Comment by eduard93** [comment]
Update MDX2JSON:
```
zn "MDX2JSON"
do ##class(MDX2JSON.Installer).Update()
```

**Comment by daimor** [comment]
If it would be so easy, this server doesn't have access to github, filled an issue there

**Comment by daimor** [comment]
solved by updating MDX2JSON
