### ISSUE TITLE
Navigation controls not working

### ISSUE THREAD

**Issue by sacen** [intersystems-ru/DeepSeeWeb#32]
In my dashboards I have navigation buttons to navigate between dashboards and copy filters from one to the other. This works in DSZ but in DSW clicking the button calls a request but it doesn't do anything

Here is my navigation button. It uses parameter SETTINGS and $$$FILTERS token

`<control name="" action="navigate" target="*" targetProperty="_DeepSee.UserPortal.DashboardViewer.zen?DASHBOARD=fnb_ds_dashboard_hosp_pohybyPacienta/PrevzatZ.dashboard&amp;SETTINGS=FILTER:$$$FILTERS" location="widget" type="auto" controlClass="" label="Převzat Z" title="Podle vybraných omezení zobrazí interní překlady Na pracoviště" value="" text="" readOnly="false" valueList="" displayList="" activeWhen="">
      <valueRequired>false</valueRequired>
    </control>`

If it is not possible to use this button, is there another way to implement navigation in DSW?

**Comment by evshvarov** [comment]
Hi, @sacen ! Only "New window" navigate control is supported at the moment. You can try to use it for your dashboard. But hope we'll add the support of other controls in near future or you can make it and send the pull request.

**Comment by evshvarov** [comment]
@sacen, you can join [skype](https://join.skype.com/f3HY4dyzQws6) and provide the case with your issue to let us fix it.
