### ISSUE TITLE
Introduce Share filtered dashboard button to share dashboard with filters

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/DeepSeeWeb#35]
Add to the DSW control panel the link Share filtered button, which will form the URL of Dashboard with current filters on widgets, to make the option to share the current data in widgets.

**Comment by evshvarov** [comment]
Cascaded filters doesn't work:
E.g. if I filter Pareto Dash with Asia and share I get the following:
http://localhost:57773/dsw/index.html#!/d/Pareto%20Charts/Pareto%20Chart%20for%20Category.dashboard?ns=samples&SETTINGS=TARGET:*;FILTER:%5BOutlet%5D.%5BH1%5D.%5BRegion%5D.%26%5BAsia%5D
If in the result dash I add another filter (e.g. Year) and share the link doesn't work.
This is the link I'm getting:
http://localhost:57773/dsw/index.html#!/d/Pareto%20Charts/Pareto%20Chart%20for%20Category.dashboard?ns=samples&SETTINGS=TARGET:*;FILTER:%5BOutlet%5D.%5BH1%5D.%5BRegion%5D.%26%5BAsia%5D&SETTINGS=TARGET:*;FILTER:%5BDateOfSale%5D.%5BActual%5D.%5BYearSold%5D.%26%5B2017%5D

**Comment by evshvarov** [comment]
Filter controls should be initialized with values from URL filter - you have the filtered data, but you don't see the filters.
Is it possible for the shared dashboard initialize filter controls (if any) and clear URL from the filters?

**Comment by evshvarov** [comment]
There should be a way to clear the URL filters: I think Home button should do the job.

**Comment by gnibeda** [comment]
Now url parameter called "Filters" and all of it values can be seen in filter input fields.
