### ISSUE TITLE
Summary of rows missing

### ISSUE THREAD

**Issue by sacen** [intersystems-ru/DeepSeeWeb#42]
Here is my setting in analyzer
![lightpivotsummary](https://cloud.githubusercontent.com/assets/25842782/23297781/1ef762a6-fa7b-11e6-95e3-2de0a4e32b86.png)

Not showing in DSW
![lightpivotsummarydsw](https://cloud.githubusercontent.com/assets/25842782/23297780/1ef67de6-fa7b-11e6-9c8a-68b2a85ea5e9.png)

**Comment by ZitRos** [comment]
Yah, summary by rows is not implemented yet. I believe it is not so trivial to do. I will try to update LPT during the week. Thanks and have a good weekend!

**Comment by ZitRos** [comment]
I apologize, the summary by rows feature is already implemented and confirmed to work in my local test environment, and on the test server (DSW 2.1.1, LPT 1.8.2):

![2017-06-19_180804](https://user-images.githubusercontent.com/4989256/27291925-5ddb0532-551a-11e7-9186-22e9c9c7ea2c.png)
![2017-06-19_180836](https://user-images.githubusercontent.com/4989256/27291926-5ddb378c-551a-11e7-96c0-bf9280c19686.png)
![2017-06-19_181412](https://user-images.githubusercontent.com/4989256/27292133-237f3d9e-551b-11e7-9e57-42cd3346c961.png)

So I cannot reproduce your issue.

@sacen, could you please create an example of the issue in Samples namespace for us? Then we will be able to investigate your problem.

**Comment by ZitRos** [comment]
Closed due to inactivity.
