### ISSUE TITLE
LPT performs right alignment for every cell

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/DeepSeeWeb#49]
http://146.185.143.59:57772/dsw/index.html#!/d/test/AlignmentBug.dashboard#%2F%3Fns=SAMPLES
It happens both for MDX and Listing modes.

It should perform left alignment for strings, and right alignment for numbers and dates

**Comment by ZitRos** [comment]
[Fixed](https://github.com/intersystems-ru/LightPivotTable/releases/tag/1.8.2).
