### ISSUE TITLE
Related filters doesn't works

### ISSUE THREAD

**Issue by ilson-** [intersystems-ru/DeepSeeWeb#6]
Hi!
Example: Cube "HoleFoods Sales".
Dimension [Product]
Level 1 [Product Category]
Level 2 [Product Name]
If I choose a "Fruit" in "Product Category" filter, 
then filter "Product Name" must contain only fruit product names.

![1](https://cloud.githubusercontent.com/assets/5246985/13731098/60b02414-e972-11e5-9e69-ff3c98e69b3e.PNG)
![2](https://cloud.githubusercontent.com/assets/5246985/13731097/60acb7f2-e972-11e5-8ebc-b0d5e93a3942.PNG)

.

**Comment by eduard93** [comment]
DSZ behavior: after user clicks on the filter to get filter values, server gets called with the following request (current filter name to get values for, all other filter values for non current filters), server answers with a list of filter values that satisfy all other set filters
DSW behavior: load all possible filter values on dashboard load in one call, do not call

DSW can mimic DSZ behavior but I think it would worsen UX, as calls take time especially on mobile etc.

**Comment by eduard93** [comment]
Note that cube dimension hierarchy has nothing to do with related filter values. When DSZ calls server for possible filter values it returns all values that satisfy all currently set filters.

**Comment by eduard93** [comment]
[Added support for related filters requests in MDX2JSON](https://github.com/intersystems-ru/Cache-MDX2JSON/commit/5e87ba70baf708f159b9c9dcf8eba0b4203981e9)
