### ISSUE TITLE
Widgets do not resize correctly on page load

### ISSUE THREAD

**Issue by alexJaegerSTR** [intersystems-ru/DeepSeeWeb#60]
Sometimes widgets do not get resized correctly directly after page load.
Manually resizing / moving will fix it and can be used as a workaround.
![resize_error_map](https://cloud.githubusercontent.com/assets/25840666/24458854/6e5830ee-149a-11e7-9bf6-c8f291107a26.PNG)

![resize_error_bar_charts](https://cloud.githubusercontent.com/assets/25840666/24458853/6e564428-149a-11e7-9c7b-d3a4199325c8.PNG)
(There should be multiple bars in each diagram)

**Comment by TsvetkovAV** [comment]
Fixed in commit 5ea7bc4
