### ISSUE TITLE
Combined charts series display type and multiple axis

### ISSUE THREAD

**Issue by alexJaegerSTR** [intersystems-ru/DeepSeeWeb#61]
Series type (bar,chart etc) and multiple y axis settings are not respected.

**Comment by evshvarov** [comment]
Reproduced here:
(http://146.185.143.59/dsw/index.html#!/d/test/Bug61.dashboard#%2F%3Fns=SAMPLES)
Series2 is of Area type, but the Line is being rendered
<img width="322" alt="2017-05-09 00 00 01" src="https://cloud.githubusercontent.com/assets/2781759/25835161/92536dd6-344a-11e7-90c3-20d9d23c291a.png">

**Comment by evshvarov** [comment]
Y axis is hidden. Check on [Pareto](http://146.185.143.59/dsw/index.html#!/f/Pareto%20Charts?ns=SAMPLES#%2F%3Fns=SAMPLES) or Combobox dashes in Samples.

**Comment by evshvarov** [comment]
Pareto charts in Samples doesn't work - Y-axis 2 is not shown. Make it work as in DSZ
