### ISSUE TITLE
Row count for listings

### ISSUE THREAD

**Issue by kusedr** [intersystems-ru/DeepSeeWeb#63]
If pivot has non empty value of parameter listingRows, DRILLTHROUGH mdx query must specify this number of rows (needed expression 'MAXROWS listingRows' ). 
E.g. 
DRILLTHROUGH **MAXROWS 20000** SELECT FROM [HOLEFOODS]

**Comment by evshvarov** [comment]
I think 20000 is good for the default, but can be also a setting in DSW settings - maxrows for listings

**Comment by evshvarov** [comment]
Fixed with 0.24
