### ISSUE TITLE
bug with formatting in LPT

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/DeepSeeWeb#69]
Bug is in LPT. Formatting works in DSZ but fails in DSW(LPT)
<img width="883" alt="screenshot 2017-07-01 10 08 59" src="https://user-images.githubusercontent.com/2781759/27759981-7a8f6c98-5e45-11e7-93c0-0384bc25211f.png">
<img width="1014" alt="screenshot 2017-07-01 10 08 36" src="https://user-images.githubusercontent.com/2781759/27759983-7cda2f38-5e45-11e7-8c82-71d5b934dad9.png">

You can check the problem online here:
https://analytics.community.intersystems.com/dsw/index.html#!/d/Reports/2017/June2017.dashboard#%2F%3Fns=COMMUNITY

**Comment by ZitRos** [comment]
Thanks Evgeny! Now fixed in [LPT v1.8.3](https://github.com/intersystems-ru/LightPivotTable/releases/tag/1.8.3), please update DSW.

**Comment by evshvarov** [comment]
Fixed by @MakarovS96 in [DSW v2.15](https://github.com/intersystems-ru/DeepSeeWeb/releases/tag/2.1.5)
