### ISSUE TITLE
Scaling problem

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/DeepSeeWeb#74]
Sometimes widgets are displayed at incorrect scale.
Steps to reproduce:
1. Open SAMPLES in DSW
2. Add 2 "widget covers"
3. Save and refresh
4. Open dashboard with widget cover
5. Go back to SAMPLES
6. Repeat 4-5.

Screenshots:
![default](https://user-images.githubusercontent.com/5127457/31073254-d1a81026-a773-11e7-9340-cfe968ebfb2f.PNG)
![1](https://user-images.githubusercontent.com/5127457/31073255-d1aabec0-a773-11e7-9231-ce05f4ad2031.PNG)
![2](https://user-images.githubusercontent.com/5127457/31073253-d1a59f1c-a773-11e7-953e-1628e517fa4a.PNG)

**Comment by TsvetkovAV** [comment]
Fixed in commit 5ea7bc4023ec058edf28bfad89a29c79ce6d323d
