### ISSUE TITLE
Don't show buttons for Data sources or Col/row lists

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/DeepSeeWeb#77]
If there is a Datasource selector on the widget there is a button nearby.
E.g. [here](http://146.185.143.59/dsw/index.html#!/d/Dynamic%20Dashboard.dashboard?ns=SAMPLES#%2F%3Fns=SAMPLES)
Do not instantiate this buttons for Data sources, Collistsspec or Rowlistsspec controls.

**Comment by eduard93** [comment]
Duplicate?
https://github.com/intersystems-ru/DeepSeeWeb/issues/67
