### ISSUE TITLE
Do not show back button for listing in LPT

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/DeepSeeWeb#81]
LPT has it's own back button. 
Or use general back UI for LPT only

**Comment by evshvarov** [comment]
![screenshot 2017-10-22 15 23 35](https://user-images.githubusercontent.com/2781759/31865442-031611ac-b73d-11e7-8d3a-4c3d953e357e.jpg)

**Comment by evshvarov** [comment]
Test case:
http://146.185.143.59/dsw/index.html#!/d/Drill%20Options.dashboard?ns=SAMPLES#%2F%3Fns=SAMPLES

**Comment by ZitRos** [comment]
Hm, I remember it worked before.

**Comment by evshvarov** [comment]
It works for the usual drilldown.
And actually "it works" even now. But if you try to go back with native LPT it confuses DSW.

**Comment by ZitRos** [comment]
I mean, there is an option in LPT which allows to hide back button, and I remember it applied for over a year ago from now. Possibly something happened and this change reverted?

**Comment by evshvarov** [comment]
Maybe. But maybe it was implemented only for drilldown, but not for drill through. Drilldown works, drillthrough not.

**Comment by ZitRos** [comment]
Do you remember, Anton?
