### ISSUE TITLE
"Metro" style doesn't work in 2.1.8

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/DeepSeeWeb#82]
Test case
http://146.185.143.59/dsw/index.html#!/?ns=SAMPLES#%2F%3Fns=SAMPLES

**Comment by gnibeda** [comment]
Can't reproduce

**Comment by evshvarov** [comment]
doesn't work in 2.1.12

**Comment by evshvarov** [comment]
Works in 2.1.12
