### ISSUE TITLE
Add "Release Onclick Filter" Functionality in Graph Widgets

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/DeepSeeWeb#89]
E.g. in Tree View: you can filter the WidgetB from Tree View, but how to release the filter once filtered?

**Comment by evshvarov** [comment]
Yes, there is BACK button on a target widget. It's good, but not right. If a target widget has a hierarchy, which is activated, and if we use click filter than, back button becomes confusing - it's not clear if it is hierarchy or filter.
It would be great if widgetA (Click filter owner) indicate the current filter selected which can be unfiltered - and this would clear the filter for all the widgets in Target field.

**Comment by gnibeda** [comment]
done

**Comment by evshvarov** [comment]
Great, it works!
Could we show the name of the filter instead of 'Reset click filter'?
